# Generated by Django 4.2 on 2023-04-27 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Underwriters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('insurer_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('insurer_detail', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('insurer_detail_2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('desgnation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email_id', models.CharField(max_length=200, unique=True)),
                ('insurer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default='NEW', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
