# Generated by Django 4.2 on 2023-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='underwriters',
            name='company_website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='underwriters',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='underwriters',
            name='location_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='underwriters',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='underwriters',
            name='profile_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
