# Generated by Django 3.2.19 on 2023-06-08 11:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('receipt_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('callback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_utilized', models.BooleanField(default=False)),
                ('json_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='PushedSTKs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mechant_app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('stk_id', models.IntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
