# Generated by Django 3.2.19 on 2023-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibspayer',
            name='payer_address',
        ),
        migrations.AddField(
            model_name='ibspayer',
            name='payer_address_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
