# Generated by Django 3.2.19 on 2023-05-20 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpolicyclass_productpolicy_number'),
        ('instalments', '0002_auto_20230520_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('monthly_fee', models.FloatField(blank=True, default=0, null=True)),
                ('initial_fee', models.FloatField(blank=True, default=0, null=True)),
                ('payment_date', models.DateTimeField(blank=True, default='', null=True)),
                ('pelnaty_type', models.CharField(blank=True, max_length=200, null=True)),
                ('pelnaty_value', models.FloatField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instalments.ibspayer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
