# Generated by Django 3.2.19 on 2023-05-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalments', '0003_instalmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalmentplan',
            name='instament_code',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
