# Generated by Django 3.2.19 on 2023-05-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalments', '0005_auto_20230524_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalmentplan',
            name='benefit_class',
        ),
    ]
