# Generated by Django 3.2.19 on 2023-05-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalments', '0006_remove_instalmentplan_benefit_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalmentplan',
            old_name='initial_fee',
            new_name='no_of_first_months',
        ),
        migrations.RenameField(
            model_name='instalmentplan',
            old_name='monthly_fee',
            new_name='no_of_instalments',
        ),
    ]
