# Generated by Django 3.2.16 on 2023-02-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('portal_user', 'portal_user'), ('portal_admin', 'portal_admin')], max_length=50, null=True),
        ),
    ]
