# Generated by Django 3.2.16 on 2023-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='bonus_awarded',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='percentage_retained',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='total_royalties',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
