# Generated by Django 3.2.16 on 2023-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230204_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='social_media',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
