# Generated by Django 3.2.16 on 2023-02-26 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountmodel_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 26, 5, 54, 42, 317760, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
