# Generated by Django 3.2.16 on 2023-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230226_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(blank=True, default='admin', max_length=50, null=True),
        ),
    ]
