# Generated by Django 4.2 on 2023-04-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accountmodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='bonus_awarded',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='passcode',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='percentage_retained',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='total_royalties',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='youtube',
        ),
    ]
