# Generated by Django 4.2 on 2023-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_accountmodel_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
