# Generated by Django 3.2.19 on 2023-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_accountmodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
