# Generated by Django 3.2.16 on 2023-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_accountmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
