# Generated by Django 3.2.16 on 2023-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accountmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='client_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
