# Generated by Django 3.2.19 on 2023-06-03 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefits', '0016_alter_productbenefits_policy_type'),
        ('products', '0004_products_policy_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.productbenefits')),
                ('benefit_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitdetails')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
