# Generated by Django 3.2.19 on 2023-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
