# Generated by Django 3.2.16 on 2023-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20230624_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policies',
            old_name='user',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='policies',
            name='business_type',
            field=models.CharField(blank=True, default='New', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='client_group',
            field=models.CharField(blank=True, default='CORPORATE', max_length=200, null=True),
        ),
    ]
