# Generated by Django 3.2.16 on 2023-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20230624_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
