# Generated by Django 3.2.16 on 2023-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_policies_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='policy_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
