# Generated by Django 3.2.16 on 2023-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20230627_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='policy_amount',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
