# Generated by Django 3.2.19 on 2023-05-20 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tax_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tax_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tax_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tax_value', models.FloatField(default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
