# Generated by Django 3.2.19 on 2023-05-24 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpolicyclass_productpolicy_number'),
        ('benefits', '0002_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBenefits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cover_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_amount', models.FloatField(blank=True, default=100000, null=True)),
                ('age_from', models.IntegerField(blank=True, default=0, null=True)),
                ('age_to', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('depedant_type', models.CharField(blank=True, default='Pricipal Member', max_length=200, null=True)),
                ('member_representation', models.CharField(blank=True, default='M+0 or M+1 or M+2', max_length=200, null=True)),
                ('gross_amount_payable', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.productbenefits')),
            ],
        ),
    ]
