# Generated by Django 3.2.19 on 2023-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_productbenefits_benefits_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitdetails',
            name='details_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
