# Generated by Django 3.2.19 on 2023-05-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalments', '0007_auto_20230524_1108'),
        ('benefits', '0005_benefitdetails_details_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbenefits',
            name='instalment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instalments.instalmentplan'),
        ),
    ]
