# Generated by Django 3.2.19 on 2023-05-24 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpolicyclass_productpolicy_number'),
        ('benefits', '0008_auto_20230524_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTaxes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.taxes')),
            ],
        ),
    ]
