# Generated by Django 3.2.19 on 2023-05-25 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_policy_class'),
        ('benefits', '0009_producttaxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.terms')),
            ],
        ),
    ]
