# Generated by Django 3.2.19 on 2023-06-02 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0010_productterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('age_to', models.IntegerField(blank=True, default=0, null=True)),
                ('age_from', models.IntegerField(blank=True, default=0, null=True)),
                ('age_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productbenefits',
            name='age_from',
        ),
        migrations.RemoveField(
            model_name='productbenefits',
            name='age_to',
        ),
    ]
