# Generated by Django 3.2.19 on 2023-06-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0011_auto_20230602_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbenefits',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.agesetup'),
        ),
    ]
