# Generated by Django 3.2.19 on 2023-06-02 23:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0012_productbenefits_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusivePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rates_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rate_cover_amount', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('limit_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.productbenefits')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dependant_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gross_payable', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('package_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.inclusivepackage')),
            ],
        ),
    ]
