# Generated by Django 3.2.19 on 2023-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0015_auto_20230603_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbenefits',
            name='policy_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
