# Generated by Django 3.2.16 on 2023-07-05 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230629_1301'),
        ('instalments', '0007_auto_20230524_1108'),
        ('benefits', '0016_alter_productbenefits_policy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(blank=True, default='NEW', max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(blank=True, default='NEW', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.provider')),
            ],
        ),
        migrations.CreateModel(
            name='BulkPlanBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('depedant_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('member_representation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gross_amount_payable', models.FloatField(blank=True, default=0, null=True)),
                ('details_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('product_value', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('manufacture_year', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('plan_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('policy_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_limit', models.FloatField(blank=True, default=1, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.agesetup')),
                ('instalment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instalments.instalmentplan')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
