# Generated by Django 3.2.16 on 2023-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0020_auto_20230707_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='applicable_to',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
