# Generated by Django 3.2.19 on 2023-05-09 14:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('kyc_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('kyctemplate_number', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCTemplateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('section_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplate')),
            ],
        ),
        migrations.CreateModel(
            name='KYCTemplateSubSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subsection_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplatesection')),
            ],
        ),
        migrations.CreateModel(
            name='SubSectionQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('field_type', models.CharField(blank=True, max_length=200, null=True)),
                ('question_number', models.CharField(blank=True, max_length=200, null=True)),
                ('defaults', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sub_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplatesubsection')),
            ],
        ),
        migrations.CreateModel(
            name='KycAnswersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.subsectionquestions')),
            ],
        ),
    ]
