# Generated by Django 3.2.19 on 2023-05-10 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyctemplate',
            name='kyc_name',
            field=models.CharField(default=datetime.datetime(2023, 5, 10, 1, 32, 36, 124064, tzinfo=utc), max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
