# Generated by Django 3.2.19 on 2023-05-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0003_alter_kyctemplate_kyc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyctemplatesection',
            old_name='name',
            new_name='section_name',
        ),
    ]
