# Generated by Django 3.2.19 on 2023-05-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0004_rename_name_kyctemplatesection_section_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyctemplatesubsection',
            old_name='name',
            new_name='sub_section_name',
        ),
    ]
