# Generated by Django 3.2.19 on 2023-05-25 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_policy_class'),
        ('KYC', '0005_rename_name_kyctemplatesubsection_sub_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.subsectionquestions')),
            ],
        ),
    ]
