# Generated by Django 3.2.19 on 2023-05-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0006_productkyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsectionquestions',
            name='sub_section',
        ),
        migrations.AddField(
            model_name='subsectionquestions',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplatesection'),
        ),
        migrations.AddField(
            model_name='subsectionquestions',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplate'),
        ),
    ]
