# Generated by Django 3.2.16 on 2023-06-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0007_auto_20230528_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycanswersmodel',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycanswersmodel',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplatesection'),
        ),
        migrations.AddField(
            model_name='kycanswersmodel',
            name='subsection_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
