# Generated by Django 3.2.16 on 2023-07-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0008_auto_20230624_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkyc',
            name='product',
        ),
    ]
