# Generated by Django 3.2.19 on 2023-05-09 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('underwriters', '0002_underwriters_company_website_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('distribution_channel', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('product_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number_of_partners', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('product_image_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number_of_policies', models.IntegerField(default=0, null=True)),
                ('product_number', models.CharField(blank=True, max_length=200, null=True)),
                ('gross_premium', models.FloatField(blank=True, default=0, null=True)),
                ('maximum_children', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('maximum_spouses', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default='NEW', max_length=200, null=True)),
                ('stamp_duty', models.FloatField(blank=True, default=0)),
                ('commission', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('underwriter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='underwriters.underwriters')),
            ],
        ),
    ]
