# Generated by Django 3.2.19 on 2023-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpolicyclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpolicyclass',
            name='productpolicy_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
