# Generated by Django 3.2.19 on 2023-05-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpolicyclass_productpolicy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='policy_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productpolicyclass'),
        ),
    ]
