# Generated by Django 3.2.16 on 2023-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_policy_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active_period',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
