# Generated by Django 3.2.16 on 2023-06-29 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_active_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPolicyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('policy_type_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('policy_type_number', models.CharField(blank=True, max_length=200, null=True)),
                ('policy_type_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='policy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productpolicytype'),
        ),
    ]
