# Generated by Django 3.2.16 on 2023-07-05 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instalments', '0007_auto_20230524_1108'),
        ('products', '0006_auto_20230629_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='commission',
            new_name='broker_commission',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gross_premium',
        ),
        migrations.RemoveField(
            model_name='products',
            name='maximum_children',
        ),
        migrations.RemoveField(
            model_name='products',
            name='maximum_spouses',
        ),
        migrations.RemoveField(
            model_name='products',
            name='number_of_partners',
        ),
        migrations.RemoveField(
            model_name='products',
            name='number_of_policies',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stamp_duty',
        ),
        migrations.CreateModel(
            name='ProductIPFDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instalment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instalments.instalmentplan')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instalments.ibspayer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
