# Generated by Django 3.2.16 on 2023-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230705_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_financed',
            field=models.CharField(blank=True, default='NEW', max_length=200, null=True),
        ),
    ]
