# Generated by Django 3.2.16 on 2023-07-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0009_remove_productkyc_product'),
        ('products', '0008_products_is_financed'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='kyc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KYC.kyctemplate'),
        ),
    ]
