# Generated by Django 3.2.16 on 2023-07-13 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpolicytype',
            name='policy_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productpolicyclass'),
        ),
        migrations.CreateModel(
            name='PolicyTypeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category_number', models.CharField(blank=True, max_length=200, null=True)),
                ('category_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('policy_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productpolicytype')),
            ],
        ),
    ]
